name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install dependencies
        run: sudo apt-get install -y libostree-dev flatpak-builder

      - name: Format
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Check
        run: cargo check

      - name: Test
        run: cargo test
